MXOline/urls.py
from django.contrib import admin
from django.urls import path
import xadmin
# from apps.users import views
from django.views.generic import TemplateView
from apps.users.views import LoginView,LogoutView
# from apps.courses.views import CourseView
# from apps.organization.views import OrgView
from django.conf.urls import url,include
from django.views.static import serve
from MXOline.settings import MEDIA_ROOT
from apps.operations.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # path('', views.index),
    # 第一种定义路由的方式
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('',IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # 配置授课机构列表展示
    # path('orglist/', OrgView.as_view(), name='orglist'),
    # 配置上传文件的访问的url
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # path('courselist/', CourseView.as_view(), name='course-list'),
    # 授课机构相关操作
    url(r'^org/', include(('apps.organization.urls', 'organization'), namespace='org')),
    # 课程相关页面
    url(r'^course/', include(('apps.courses.urls', 'courses'), namespace='course')),
    # 用户操作相关
    url(r'^op/', include(('apps.operations.urls', 'operations'), namespace='op')),
    url(r'^users/', include(('apps.users.urls', 'users'), namespace='users')),

]

apps/courses/urls.py
from django.conf.urls import url
from apps.courses.views import *
urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='list'),
    # url(r'^detail/$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<course_id>\d+)/lesson/$', CourseLessonView.as_view(), name='lesson'),
    url(r'^(?P<course_id>\d+)/comment/$', CourseCommentsView.as_view(), name='comment'),
    url(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)$', VideoView.as_view(), name='video'),
]

apps/organization/urls.py
from django.conf.urls import url,include
from apps.organization.views import *
urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name='list'),
    url(r'^add_ask/$', AddAsk.as_view(), name='add_ask'),
    # 讲师相关
    url(r'^teachers/$', TeacherListView.as_view(), name='teachers'),
    url(r'^teachers/(?P<teacher_id>\d+)$', TeacherDeatailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from apps.users.views import *

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='info'),

    # url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),
    url(r'^mycourse/$', login_required(TemplateView.as_view(template_name='usercenter-mycourse.html'), login_url = '/login/'), {"current_page": "mycourse" }, name='mycourse'),
    url(r'^myfav-course/$', login_required(TemplateView.as_view(template_name='usercenter-fav-course.html'), login_url = '/login/'), {"current_page": "myfav" }, name='myfav-course'),
    url(r'^myfav-org/$', login_required(TemplateView.as_view(template_name='usercenter-fav-org.html'), login_url = '/login/'), {"current_page": "myfav" }, name='myfav-org'),
    url(r'^myfav-teacher/$', login_required(TemplateView.as_view(template_name='usercenter-fav-teacher.html'), login_url = '/login/'), {"current_page": "myfav" }, name='myfav-teacher'),
    url(r'^message/$', login_required(TemplateView.as_view(template_name='usercenter-message.html'), login_url = '/login/'), {"current_page": "message" }, name='message'),

]

apps/courses/models.py
from datetime import datetime

from django.db import models

from apps.users.models import BaseModel
from apps.organization.models import Teacher
from apps.organization.models import CourseOrg

from DjangoUeditor.models import UEditorField

#1. 设计表结构有几个重要的点
"""
实体1 <关系> 实体2
课程 章节 视频 课程资源
"""
#2. 实体的具体字段

#3. 每个字段的类型，是否必填


class Course(BaseModel):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="讲师")
    course_org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name="课程机构")
    name = models.CharField(verbose_name="课程名", max_length=50)
    desc = models.CharField(verbose_name="课程描述", max_length=300)
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    degree = models.CharField(verbose_name="难度", choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), max_length=2)
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    notice = models.CharField(verbose_name="课程公告", max_length=300, default="")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name="课程类别")
    tag = models.CharField(default="", verbose_name="课程标签", max_length=10)
    youneed_know = models.CharField(default="", max_length=300, verbose_name="课程须知")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name="老师告诉你")
    is_classics = models.BooleanField(default=False, verbose_name="是否经典")
    # detail = UEditorField(verbose_name="课程详情", width=600, height=300, imagePath="courses/ueditor/images/",
    #                       filePath="courses/ueditor/files/", default="")
    detail = models.CharField(verbose_name="课程详情", max_length=500)
    is_banner = models.BooleanField(default=False, verbose_name="是否广告位")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="封面图", max_length=100)

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        return self.lesson_set.all().count()

    def show_image(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<img src='{}'>".format(self.image.url))
    show_image.short_description = "图片"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='/course/{}'>跳转</a>".format(self.id))
    go_to.short_description = "跳转"


class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    tag = models.CharField(max_length=100, verbose_name="标签")

    class Meta:
        verbose_name = "课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")  #on_delete表示对应的外键数据被删除后，当前的数据应该怎么办
    name = models.CharField(max_length=100, verbose_name="章节名")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")

    class Meta:
        verbose_name = "课程章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(BaseModel):
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    url = models.CharField(max_length=1000, verbose_name=u"访问地址")

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="下载地址", max_length=200)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/course-comment.html
{% extends 'base.html' %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">

                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:list' %}">公开课</a>></li>
                {#        <li><a href="{% url 'course:detail' %}">课程详情</a>></li>#}
                <li>课程评论</li>

            </ul>
        </div>
    </section>
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/course-comment.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css">
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css">
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css"/>
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"
                                       href="{% url 'course:lesson' course.id %}"><span>章节</span></a>
                                </li>
                                <li><a id="commentOn" class="active" href="{% url 'course:comment' course.id %}"><span>评论</span></a>
                                </li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in comments %}
                                    <li class="post-row">
                                        <div class="media">
                                        <span target="_blank"><img src='{{ comment.user.image.url }}'
                                                                   width='40' height='40'/></span>
                                        </div>
                                        <div class="bd">
                                            <div class="tit">
                                            <span target="_blank">
                                                {% if comment.user.nick_name %}
                                                    {{ comment.user.nick_name }}
                                                {% else %}
                                                    {{ comment.user.username }}
                                                {% endif %}
                                            </span>
                                            </div>
                                            <p class="cnt">
                                                {{ comment.comments }}</p>
                                            <div class="footer clearfix">
                                                <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}


                            </ul>
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for resource in course_resource %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                            <a href="{{ resource.file.url }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}


                                </ul>
                            </div>

                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="/u/315464/courses?sort=publish" target="_blank">
                                        <img src='{{ course.teacher.image.url }}' width='80'
                                             height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="#" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>

                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in related_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:detail' course.id %}" target="_blank">
                                                        <img src="{{ course.image.url }}"
                                                             alt="{{ course.name }}">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}


                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                         alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        //添加评论
        $(document).ready(function () {
            $('#js-pl-submit').on('click', function () {
                var comments = $("#js-pl-textarea").val()
                if (comments == "") {
                    alert("评论不能为空")
                    return
                }
                $.ajax({
                    cache: false,
                    type: "POST",
                    url:"{% url 'op:comment'%}",
                    data: {'course': {{ course.id }}, 'comments': comments},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'fail') {
                            if (data.msg == '用户未登录') {
                                window.location.href = "{% url 'login' %}";;
                            } else {
                                alert(data.msg)
                            }

                        } else if (data.status == 'success') {
                            window.location.reload();//刷新当前页面.
                        }
                    },
                });
            });
        });

    </script>
{% endblock %}

templates/course-video.html
{% extends 'base.html' %}
{% block title %}公开课视频信息-慕学在线网{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:detail' course.id %}">课程详情</a>></li>
                    <li>章节信息</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"
                                       href="{% url 'course:lesson' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="" href="{% url 'course:comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <div id="notice" class="clearfix">
                            <div class="l"><strong>课程公告:</strong> <a
                                    href="javascript:void(0)">{{ course.notice }}</a></div>
                        </div>

                        <div class="mod-chapters">
                            {% for lesson in course.lesson_set.all %}
                                <div class="chapter chapter-active">
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">
                                        {% for video in lesson.video_set.all %}
                                            <li>
                                                <a target="_blank" href='{% url 'course:video' course.id video.id %}'
                                                   class="J-media-item studyvideo">{{ video.name }}
                                                    <i class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}


                                    </ul>
                                </div>
                            {% endfor %}


                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for resource in course_resource %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                            <a href="{{ resource.file.url }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}


                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="/u/315464/courses?sort=publish" target="_blank">
                                        <img src='{{ course.teacher.image.url }}' width='80'
                                             height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="#" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in related_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:detail' course.id %}" target="_blank">
                                                        <img src="{{ course.image.url }}"
                                                             alt="{{ course.name }}">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}


                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                         alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}我的收藏-慕学在线网{% endblock %}
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_form %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% if request.path|slice:'14' == '/users/myfav-o' %}active{% endif %}"><a href="{% url 'users:myfav-org' %}">课程机构</a> </li>
                        <li class="{% if request.path|slice:'14' == '/users/myfav-t' %}active{% endif %}"><a href="{% url 'users:myfav-teacher' %}">授课教师 </a></li>
                        <li class="{% if request.path|slice:'14' == '/users/myfav-c' %}active{% endif %}"><a href="{% url 'users:myfav-course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">

                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="/static/media/courses/2016/12/57035ff200014b8a06000338-240-135_dHfj8Nq.jpg"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>scrapy教程</h2></a>
                                <span class="fl">时长：<i class="key">55</i></span>
                                <span class="fr">学习人数：0</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">北京大学</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>

                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="/static/media/courses/2016/12/mysql.jpg"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>xadmin进阶开发</h2></a>
                                <span class="fl">时长：<i class="key">30</i></span>
                                <span class="fr">学习人数：2</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">慕学网</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="13"></span>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
{% endblock %}